using System;
using System.Collections.Generic;
using System.Text;

namespace Kaltar.Talentos {

    public enum IdHabilidadeTalento : int {
        bloquear,
        focoArmaEspada,
        focoArmaMaca,
        focoArmaMachado,
        focoArmaArco,
        focoArmaPunho,
        focoArmaEsgrima,
        especializacaoArmaEspada,
        especializacaoArmaMaca,
        especializacaoArmaMachado,
        especializacaoArmaArco,
        especializacaoArmaPunho,
        especializacaoArmaEsgrima,
        focoCriticoEspada,
        focoCriticoMaca,
        focoCriticoMachado,
        focoCriticoArco,
        focoCriticoPunho,
        focoCriticoEsgrima,
        agil,
        sagaz,
        robusto,
        danoCriticoEspada,
        danoCriticoMachado,
        danoCriticoMaca,
        danoCriticoEsgrima,
        danoCriticoPunho,
        danoCriticoArco,
        torre,
        tenacidade,
        assassinoDasSombras,
        armaPerfurante,
        aptiddaoMagica,
        absorverMana,
        magiaEstendida,
        poderEstendido,
        retribuicaoDaF,
        conservarMana,
        familiar,
        peleDeferro,
        resistenciaElemental,
        couroDeCobra,
        filhoDeCobra,
        agilidadeComArma,
        duroDeMatar,
        folegoDeAtleta,
        mentalização,
        flanquear,
        emboscada,
        revitalizacaoDeCombate,
        folegoDeCombate,
        manaDeCombate,
        contraAtaque,
        defesaRevigorante,
        olhosDeAguia,
        criticoParalisante,
        empatiaComAnimais,
        conjuracaoResistente,
        conjuracaoForte,
        conjuracaoExtendida,
        vozAnimal,
        poderDaFe,
        regeneracaoAprimorada,
        folegoAprimorado,
        manaAprimorado,
        folegoRevigorante,
        manaRevigorante
    }

}
